### ISSUE TITLE
ConcurrentModificationException

### ISSUE THREAD

**Issue by Lathomas42** [ninscope/Software#2]
When I try to run the processing app on OSX Ventura with processing v4.2 I get:

java.util.ConcurrentModificationException
	at java.base/java.util.LinkedList$ListItr.checkForComodification(LinkedList.java:970)
	at java.base/java.util.LinkedList$ListItr.next(LinkedList.java:892)
	at g4p_controls.GWindow.post(Unknown Source)
	at jdk.internal.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at processing.core.PApplet$RegisteredMethods.handle(PApplet.java:1309)
	at processing.core.PApplet.handleMethods(PApplet.java:1456)
	at processing.core.PApplet.handleDraw(PApplet.java:2119)
	at processing.awt.PSurfaceAWT$9.callDraw(PSurfaceAWT.java:1388)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:356)
ConcurrentModificationException

**Comment by andresdegroot** [comment]
Hi @Lathomas42 ,
The NINscope software is developed for processing 3.5.4. 
You can download 3.5.4 using the link in this section : [https://github.com/ninscope/Software/wiki/NINscope-software .](https://github.com/ninscope/Software/wiki/NINscope-software#supported-versions-of-processing) .
